[compiler.solc]
remappings = [
  "openzeppelin/contracts/=smart-contracts/lib/risc0-ethereum/lib/openzeppelin-contracts/contracts/",
  "risc0-ethereum/=smart-contracts/lib/risc0-ethereum/contracts/src/",
  "forge-std/=smart-contracts/lib/forge-std/src/",
]
exclude_paths = [
  "smart-contracts/lib/**",
  "smart-contracts/test/**",
  "smart-contracts/lib/risc0-ethereum/lib/**",
  "smart-contracts/lib/risc0-ethereum/crates/**",
  "smart-contracts/lib/risc0-ethereum/contracts/**",
]