FROM ghcr.io/foundry-rs/foundry:stable

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash \
        make \
        python3 \
        python3-pip \
        python3-venv \
        python3-dev \
        jq \
        openssh-client \
        curl \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*
